<?php
namespace ExchangeAndroidClasses;
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserOperator.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-13 at 15:55:08.
 */
class DB_UserOperatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DB_UserOperator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_UserOperator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ExchangeAndroidClasses\DB_UserOperator::getUserByEmail
     * @todo   Implement testGetUserByEmail().
     */
    public function testGetUserByEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExchangeAndroidClasses\DB_UserOperator::getUserById
     * @todo   Implement testGetUserById().
     */
    public function testGetUserById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExchangeAndroidClasses\DB_UserOperator::deleteUserById
     * @todo   Implement testDeleteUserById().
     */
    public function testDeleteUserById()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExchangeAndroidClasses\DB_UserOperator::updateUser
     * @todo   Implement testUpdateUser().
     */
    public function testUpdateUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExchangeAndroidClasses\DB_UserOperator::createUser
     * @todo   Implement testCreateUser().
     */
    public function testCreateUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
