<?php
namespace ExchangeAndroidClasses;
require_once __DIR__.'..\..\ExchangeAndroidClasses\ExtremeController.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\UserController.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\Controller.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserOperator.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_MobileUser.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserTask.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\TaskController.php';
require_once './Test_DB_Connector.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-06 at 11:45:42.
 */
class ExtremeControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExtremeController
     */
    protected $extremeController;
    
    /**
     * @var Test_DB_Connector
     */
    protected $testDbConnector;
    
    /**
     *
     * @var DB_UserOperator;
     */
    protected $dbUserOperator;
    
    /**
     * @var DB_TaskOperator
     */
    protected $db_TaskOperator;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->extremeController = new ExtremeController();
        $this->dbUserOperator = new DB_UserOperator();
        $this->db_TaskOperator = new DB_TaskOperator();
        $this->testDbConnector = new Test_DB_Connector();
        $this->testDbConnector->clearDataFromTables();
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->testDbConnector->clearDataFromTables();
    }

    /**
     * @return DB_MobileUser 
     */
    private function createUser(){
        /**
         * @var DB_MobileUser Description
         */
        $user = new DB_MobileUser();
        $user->setUser_email("sergo3030@mail.ru");
        $user->setUser_login("jarjarbinks");
        $user->setUser_password("123456");
        $this->dbUserOperator->createUser($user, $db_error);
        if ($db_error == FALSE){
            $user->setUser_password("123456");
            return $user;
        }            
        else{
            return FALSE;
        }
    }
    /**
     * 
     * @param DB_MobileUser $user
     * @return void Description
     */
    private function createTaskListInDB($user){
        $db_error = FALSE;
        for ($i = 0; $i < 5; $i++){
            $data = date('Y-m-d H:i:s');
            $task_array['task_type'] = 'type1';
            $task_array['user_id'] = $user->getUser_id();
            $task_array['task_file_name'] = 'filename'.$i;
            $task_array['task_instruction'] = 'instruction'.$i;
            $task_array['task_image_small'] = 'task_image_small.$i';
            $task_array['task_image_large'] = 'task_image_large'.$i;
            $task_array['task_date_create'] = $data;
            $task_array['task_date_last_modify'] = $data;
            $task_array['task_date_last_use'] = $data;
            $task_array['task_usage_count'] = 0;
            $task_array['task_is_favorite'] = 'no';
            $userTask = new DB_UserTask();
            $userTask->setAllFromArray($task_array);
            $this->db_TaskOperator->insertTask($userTask, $db_error);    
        }
        return !$db_error;
        
    }


    /**
     * @covers ExchangeAndroidClasses\ExtremeController::executeRequest
     * @todo   Implement testExecuteRequest().
     */
    public function testExecuteRequest()
    {
        $user = $this->createUser();
        $taskCreated = FALSE;
        $db_error = FALSE;
        if($user->getUser_id()){
            $taskCreated = $this->createTaskListInDB($user);
        }
        $this->assertTrue($taskCreated);
        $request[Controller::ACTION] = Controller::REMOVE_ALL_ACTION;
        $request[Controller::USER] = $user->getObjectAsJson();
        $this->extremeController->executeRequest($request);
        $newUser = $this->dbUserOperator->getUserById($user->getUser_id(), $db_error);
        $this->assertFalse($newUser->getUser_id());
        $tasklist = $this->db_TaskOperator->getTaskListByUserID($user->getUser_id(), $db_error);
        $this->assertFalse($tasklist);
        
    }
}
