<?php
namespace ExchangeAndroidClasses;
require_once __DIR__.'..\..\ExchangeAndroidClasses\UserController.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\Controller.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserOperator.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_MobileUser.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserTask.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\TaskController.php';
require_once './Test_DB_Connector.php';
require_once './TestHelper.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-17 at 14:11:12.
 */
class TaskControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TaskController
     */
    protected $taskController;
    
    
    
    
    
    /**
     *
     * @var Test_DB_Connector
     */
    protected $testDbConnector;
    
    
    /**
    *
    * @var TestHelper
    */
    private $testHelper;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->taskController = new TaskController();
        
        $this->testDbConnector = new Test_DB_Connector();
       
        $this->testHelper = new TestHelper();
        
        $this->testDbConnector->clearDataFromTables();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->testDbConnector->clearDataFromTables();
    }

   
    
   
    
   public function testExecuteRequestCreateTask(){
    $dbUser = $this->testHelper->createUser();
    $task = $this->testHelper->getTask($dbUser);
    $request[Controller::ACTION] = Controller::CREATE_TASK;
    $request[Controller::USER] = $dbUser->getObjectAsJson();
    $request[Controller::TASK] = $task->getObjectAsJson();
    $result = $this->taskController->executeRequest($request);
    $result = json_decode($result,true);
    $this->assertTrue(isset($result[Controller::TASK]));
    $this->assertTrue(isset($result[Controller::ERRORS]));
    $this->assertTrue($result[Controller::ERRORS] == FALSE);
    $registeredTask = new DB_UserTask();
    $registeredTask->setObjectFieldsFromJson($result[Controller::TASK]);
    $this->assertTrue($registeredTask->getTask_id() > 0);
    $task->setTask_id($registeredTask->getTask_id());
    $this->assertEquals($task->getObjectAsJson(), $registeredTask->getObjectAsJson());
 
   }
    
   public function testExecuteRequestUpdateTask(){
        $dbUser = $this->testHelper->createUser();
        $task = $this->testHelper->getTask($dbUser);
        $request[Controller::ACTION] = Controller::CREATE_TASK;
        $request[Controller::USER] = $dbUser->getObjectAsJson();
        $request[Controller::TASK] = $task->getObjectAsJson();
        $result = $this->taskController->executeRequest($request);
        $result = json_decode($result,true);
        $this->assertTrue(isset($result[Controller::TASK]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $this->assertTrue($result[Controller::ERRORS] == FALSE);
        $registeredTask = new DB_UserTask();
        $registeredTask->setObjectFieldsFromJson($result[Controller::TASK]);
        $this->assertTrue($registeredTask->getTask_id() > 0);
        $task->setTask_id($registeredTask->getTask_id());
        $this->assertEquals($task->getObjectAsJson(), $registeredTask->getObjectAsJson());
        $task->setTask_instruction("New instruction");
        $request[Controller::ACTION] = Controller::UPDATE_TASK;
        $request[Controller::USER] = $dbUser->getObjectAsJson();
        $request[Controller::TASK] = $task->getObjectAsJson();
        $result = $this->taskController->executeRequest($request);
        $result = json_decode($result, true);
        $this->assertTrue(isset($result[Controller::UPDATED]));
        $this->assertTrue($result[Controller::UPDATED]);
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $this->assertFalse($result[Controller::ERRORS]);
   }
   
   
   public function testExecuteRequestDeleteTask(){
        $dbUser = $this->testHelper->createUser();
        $task = $this->testHelper->getTask($dbUser);
        $request[Controller::ACTION] = Controller::CREATE_TASK;
        $request[Controller::USER] = $dbUser->getObjectAsJson();
        $request[Controller::TASK] = $task->getObjectAsJson();
        $result = $this->taskController->executeRequest($request);
        $result = json_decode($result,true);
        $this->assertTrue(isset($result[Controller::TASK]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $this->assertTrue($result[Controller::ERRORS] == FALSE);
        $registeredTask = new DB_UserTask();
        $registeredTask->setObjectFieldsFromJson($result[Controller::TASK]);
        $this->assertTrue($registeredTask->getTask_id() > 0);
        $request[Controller::ACTION] = Controller::DELETE_TASK;
        $request[Controller::USER] = $dbUser->getObjectAsJson();
        $request[Controller::TASK] = $registeredTask->getObjectAsJson();
        $result = $this->taskController->executeRequest($request);
        $result = json_decode($result, true);
        $this->assertTrue(isset($result[Controller::DELETED]));
        $this->assertTrue($result[Controller::DELETED]);
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $this->assertFalse($result[Controller::ERRORS]);
   }
    
    
    
    /**
     * @covers ExchangeAndroidClasses\TaskController::executeRequest
     * @todo   Implement testExecuteRequest().
     */
    
       
    public function testExecuteRequestGetTaskList()
    {
          $dbUser = $this->testHelper->createUser();
          $inserted = $this->testHelper->createTaskListInDB($dbUser);
          $this->assertTrue($inserted);
          $request[Controller::ACTION] = Controller::TASK_LIST;
          $request[Controller::USER] = $dbUser->getObjectAsJson();
          $result = $this->taskController->executeRequest($request);
          $result = json_decode($result, true);
          $this->assertTrue(isset($result[Controller::ERRORS]));
          $this->assertTrue(isset($result[Controller::TASK_LIST]));
          $this->assertFalse($result[Controller::ERRORS]);
          
    }
}
