<?php
namespace ExchangeAndroidClasses;
require_once __DIR__.'..\..\ExchangeAndroidClasses\UserController.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-13 at 16:04:29.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ExchangeAndroidClasses\UserController::executeRequest
     * @todo   Implement testExecuteRequest().
     */
    public function testExecuteRequest()
    {   
        $this->assertTrue(TRUE);
        // Remove the following lines when you implement this test.
        
    }
}
