<?php
namespace ExchangeAndroidClasses;
require_once __DIR__.'..\..\ExchangeAndroidClasses\UserController.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\Controller.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_UserOperator.php';
require_once __DIR__.'..\..\ExchangeAndroidClasses\DB_MobileUser.php';
require_once './Test_DB_Connector.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-13 at 16:04:29.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserController
     */
    protected $object;
    protected $testDbConnector;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserController();
        $this->testDbConnector = new Test_DB_Connector();
        $this->testDbConnector->clearDataFromTables();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->testDbConnector->clearDataFromTables();
    }

    /**
     * @covers ExchangeAndroidClasses\UserController::executeRequest
     * @todo   Implement testExecuteRequest().
     */
    public function testExecuteRequest()
    {   
       /* $request[Controller::ACTION] = Controller::REGISTER_ACTION;
        $request['userlogin'] = 'sergo';
        $request['useremail'] = 'sergo3030@mail.ru';
        $request['userpassword'] = 'amber2000';
        $result = $this->object->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $user = new DB_MobileUser;
        $user->setObjectFieldsFromJson($result[Controller::USER]);
        $user->setUser_password('amber2000');
        $this->assertTrue($user->getUser_id() > 0);
        $this->assertTrue($user->getUser_login() == $request['userlogin']);
        $this->assertTrue($user->getUser_email() == $request['useremail']);
        $this->assertTrue($user->isPaswordCorrect($request['userpassword']));
        $this->assertFalse($result[Controller::ERRORS]);
        $request[Controller::ACTION] = Controller::LOGIN_ACTION;
        $result = $this->object->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $loginedUser = new DB_MobileUser;
        $loginedUser->setObjectFieldsFromJson($result[Controller::USER]);
        $this->assertEquals($loginedUser->getCheckSum(), $user->getCheckSum());
        
        $request[Controller::ACTION] = Controller::LOGIN_ACTION;
        $request['useremail'] = 'sergo4040@mail.ru';
        $result = $this->object->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $loginedUser = new DB_MobileUser;
        $loginedUser->setObjectFieldsFromJson($result[Controller::USER]);
        $emptyUser = new DB_MobileUser;
        $this->assertEquals($emptyUser->getCheckSum(), $loginedUser->getCheckSum());
        //$this->assertEquals($result[Controller::ERRORS], Controller::ERROR_PASSWORD_USER_INCORRECT);  */   
    }
    
    public function testExecuteRequestRegisterUser(){
        $userController = new UserController();
        $request[Controller::ACTION] = Controller::REGISTER_ACTION;
        $request['userlogin'] = 'sergo';
        $request['useremail'] = 'sergo3030@mail.ru';
        $request['userpassword'] = 'amber2000';
        $result = $userController->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        
    }
    
    
    public function testExecuteRequestLoginUser(){
         $userController = new UserController();
        $request[Controller::ACTION] = Controller::REGISTER_ACTION;
        $request['userlogin'] = 'sergo';
        $request['useremail'] = 'sergo3030@mail.ru';
        $request['userpassword'] = 'amber2000';
        $result = $userController->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $user = new DB_MobileUser();
        $user->setObjectFieldsFromJson($result[Controller::USER]);
        $user->setUser_password('amber2000');
        
        $request[Controller::ACTION] = Controller::LOGIN_ACTION;
        $request['userlogin'] = 'sergo';
        $request['useremail'] = 'sergo3030@mail.ru';
        $request['userpassword'] = 'amber2000';
        $result = $userController->executeRequest($request);
        $result = json_decode($result, TRUE);
        $this->assertTrue(isset($result[Controller::USER]));
        $this->assertTrue(isset($result[Controller::ERRORS]));
        $userExisted = new DB_MobileUser();
        $userExisted->setObjectFieldsFromJson($result[Controller::USER]);
        
        $this->assertTrue($result[Controller::ERRORS] == FALSE);
        
    }
}
